name: CI

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Install
        run: yarn

      - name: Build
        run: yarn test

      - name: ESLint + Prettier
        run: yarn lint
